version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DATABASE}
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${SPRING_MONGODB_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${SPRING_MONGODB_PASSWORD}
    networks:
      - default
    volumes:
      - mongodb-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - "15672:15672"
    environment:
      RABBITMQ_TRANSACTION_QUEUE_NAME: ${RABBITMQ_TRANSACTION_QUEUE_NAME}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - default

  transactions:
    build:
      context: .
      dockerfile: ./transactions-service/Dockerfile-transactions
    restart: always
    depends_on:
      - mysql
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_MONGODB_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_MONGODB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_MONGODB_PASSWORD}
      SECURITY_JWT_PUBLIC_KEY_FILE: ${SECURITY_JWT_PUBLIC_KEY_FILE}
      SECURITY_JWT_SECRET_KEY_FILE: ${SECURITY_JWT_SECRET_KEY_FILE}
    ports:
      - ${TRANSACTIONS_SERVICE_PORT}:${TRANSACTIONS_SERVICE_PORT}
    networks:
      - default

  users:
    build:
      context: .
      dockerfile: ./users-service/Dockerfile-users
    restart: always
    depends_on:
      - mongodb
    environment:
      SPRING_MONGODB_URL: ${SPRING_MONGODB_URL}
      SPRING_MONGODB_USERNAME: ${SPRING_MONGODB_USERNAME}
      SPRING_MONGODB_PASSWORD: ${SPRING_MONGODB_PASSWORD}
      SECURITY_JWT_PUBLIC_KEY_FILE: ${SECURITY_JWT_PUBLIC_KEY_FILE}
      SECURITY_JWT_SECRET_KEY_FILE: ${SECURITY_JWT_SECRET_KEY_FILE}
    ports:
      - ${USERS_SERVICE_PORT}:${USERS_SERVICE_PORT}
    networks:
      - default

networks:
  default:
    name: user-transactions-services_default

volumes:
  mysql-data:
  rabbitmq-data:
  mongodb-data:
