name: Pull Request Build and Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        run: |
          docker-compose docker-compose.yml build
          docker-compose docker-compose.yml up -d

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml exec -T transactions mvn test
          docker-compose -f docker-compose.yml exec -T users mvn test
          docker-compose -f docker-compose.yml exec -T auth mvn test

      - name: Shutdown Docker Compose
        run: |
          docker-compose -f docker-compose.yml down