name: Pull Request Build and Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_DATABASE: 'user-transactions'
      SPRING_DATASOURCE_PASSWORD: 'root'
      RABBITMQ_PORT: '5672'
      RABBITMQ_TRANSACTION_TO_USER_QUEUE_NAME: 'default.transaction-queue'
      RABBITMQ_USER_TO_TRANSACTION_QUEUE_NAME: 'default.user-queue'
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/user-transactions'
      SPRING_DATASOURCE_USERNAME: 'root'
      RABBITMQ_HOST: 'amqp://guest:guest@rabbitmq:5672/'
      SECURITY_JWT_PUBLIC_KEY_FILE: 'classpath:security.pub'
      SECURITY_JWT_SECRET_KEY_FILE: 'classpath:security.key'
      SECURITY_API_KEY: 'daf75259-2374-417b-b86b-27556f0ab933'
      TRANSACTIONS_SERVICE_PORT: '8081'
      USERS_SERVICE_PORT: '8080'
      USERS_SERVICE_URL: 'http://users:8080'
      AUTH_SERVICE_PORT: '8082'
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose up -d

      - name: Run tests
        run: |
          docker run --rm -v $(pwd)/transactions-service:/app -w /app maven:3.8.5-openjdk-17 mvn test
          docker run --rm -v $(pwd)/users-service:/app -w /app maven:3.8.5-openjdk-17 mvn test
          docker run --rm -v $(pwd)/auth-service:/app -w /app maven:3.8.5-openjdk-17 mvn test

      - name: Shutdown Docker Compose
        run: |
          docker-compose -f docker-compose.yml down